apiVersion: v1
kind: Service
metadata:
  name: git-ops-svc
spec:
  selector:
    name: git-ops-demo
    env: dev
    project: sample-project
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: "tcp"
      nodePort: 32100
      name: "git-ops"